### ISSUE TITLE
BEETLE Algorithm

### ISSUE THREAD

**Issue by Guyanqi** [cuhkrlcourse/RLexample#1]
Is there an implementation of BEETLE algorithm from paper "An Analytic Solution to Discrete bayesian RL"? Thanks!

**Comment by pengzhenghao** [comment]
Sorry, but here is a collection of implementations of classical RL algorithms for teaching purposes, most of which are collected from open-source projects. So currently we do not provide the implementation you asked. Maybe you can search Github or ask the authors for this.
