### ISSUE TITLE
No module named 'gym.envs.atari'

### ISSUE THREAD

**Issue by lovesuiyue** [cuhkrlcourse/RLexample#14]

**Comment by lovesuiyue** [comment]
有谁知道阿

**Comment by pengzhenghao** [comment]
请安装gym的配套库：

```
pip install gym[all]==0.18.0
```

正如我们在首页配置环境部分所写：

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/22206995/140267040-bc7310cc-4e0c-4959-b745-2f989b2eef9c.png">

谢谢！
