### ISSUE TITLE
Question about the policy evaluation function and policy extraction of the MDP code

### ISSUE THREAD

**Issue by xiezhy6** [cuhkrlcourse/RLexample#9]
Hi, thanks for your course! It helps me a lot.

I have some question about the code in [frozenlake_policy_iteration.py](https://github.com/cuhkrlcourse/RLexample/blob/master/MDP/frozenlake_policy_iteration.py). Why is the expression of the value fuction in compute_policy_v (line 52) same as the state-action function in compute_policy_v (line37) ?

And why is the expression of the value function `v[s] = sum([p * (r + gamma * prev_v[s_]) for p, s_, r, _ in env.env.P[s][policy_a]])` different from the formula(17) in the slide? It seems that the expression in the code ignore the transition probability P(s'|s,a)?

Thanks! Look forward your reply~

**Comment by pengzhenghao** [comment]
【Why is the expression of the value fuction in compute_policy_v (line 52) same as the state-action function in compute_policy_v (line37) ?】
The action is different, so even though the equation is the same, the meaning of such lines is different.

【It seems that the expression in the code ignore the transition probability P(s'|s,a)?】
`for p, s_, r, _ in env.env.P[s][policy_a]` in [this line](https://github.com/cuhkrlcourse/RLexample/blob/master/MDP/frozenlake_policy_iteration.py#L52) is exactly the transition probability, so it is not ignored.

Feel free to reopen this issue if you have further question
